#!/bin/bash -ex

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd $DIR
node test_kcn.js
node test_rtm.js
node test.js
node test_autolykos2.js
node test_ethash.js
node test_etchash.js
node test_kawpow.js
node test_astrobwt.js
node test_astrobwt2.js
node test_k12.js
node test_sync-1.js
node test_sync-2.js
node test_sync-r.js
node test_sync-half.js
node test_sync-msr.js
node test_sync-xao.js
node test_sync-rto.js
node test_sync-gpu.js
node test_sync-rwz.js
node test_sync-zls.js
node test_sync-ccx.js
node test_sync-double.js
node test_sync.js
node test_sync_light.js
node test_sync_light-1.js
node test_sync_heavy.js
node test_sync_heavy-xhv.js
node test_sync_heavy-tube.js
node test_sync_pico.js
node test_rx0.js
node test_rx_xeq.js
node test_rx_arq.js
#node test_rx_defyx.js
node test_rx_xla.js
#node test_rx_wow.js
#node test_rx_loki.js
#node test_rx_keva.js
#node test_rx_graft.js
node test_rx_switch.js
node test_ar2_chukwa.js
node test_ar2_chukwa2.js
node test_ar2_wrkz.js

node test_perf_kcn.js
node test_perf_rtm.js
node test_perf.js
node test_perf_xla.js
node test_perf_kawpow.js
node test_perf_ethash.js
node test_perf_astrobwt.js
node test_perf_astrobwt2.js
node test_perf_k12.js
node test_perf_light.js
node test_perf_heavy.js
node test_perf_gpu.js
#node test_perf_rx_defyx.js
node test_perf_rx_wow.js
#node test_perf_rx_loki.js
#node test_perf_rx_keva.js
#node test_perf_rx_graft.js
node test_perf_rx_switch.js
node test_perf_pico.js
node test_perf_double.js
node test_perf_ar2_chukwa2.js
node test_perf_ar2_wrkz.js
